openapi: 3.0.0
info:
  title: Elevator Maintenance API
  version: 1.0.0
  description: API for elevator maintenance using Express.js

paths:
  /elevators:
    get:
      summary: Get a list of elevators
      responses:
        '200':
          description: Successful response

  /elevators/count:
    get:
      summary: Get elevator counts by state
      responses:
        '200':
          description: Successful response

  /elevators/elevators-list/{state}:
    parameters:
      - name: state
        in: path
        required: true
        schema:
          type: string
        description: Elevator state (e.g., warning, out-of-order, operational)
    get:
      summary: Get a list of elevators by state (e.g., warning, out-of-order, operational)
      responses:
        '200':
          description: Successful response


  /elevators/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: Fabrication number (e.g., FAB138)
    get:
      summary: Get elevator details by fabrication number (e.g., FAB138)
      responses:
        '200':
          description: Successful response

